# version: '3'
# services:
#   fastapi-app:
#     build: .
#     image: fastapi-app-secretflow-app
#     ports:
#       - 80:8000
#     restart: always
#     shm_size: "2.45gb"
#     volumes:
#       - ./app:/code/app  # Mount your local app directory to the container
services:
  fastapi-app:
    build: .
    ports:
      - "80:80"
    shm_size: "2.45gb"
    volumes:
      - ./app:/code/app 
      - ./src:/code/src